model:

  
# Vivos
training:
  epochs: 100
  batch_size: 3
  accumulation_steps: 1
  save_path: "C:/paper/self-acoustic/save_folder"
  train_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/train_w2i.json"
  dev_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/test_w2i.json"
  test_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/test_w2i.json"
  vocab_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/vocab_w2i.json"
  cmvn_stats : "workspace/rna/conv-rnnt/data/cmvn_stats.pt"
  log_path: "C:/paper/self-acoustic/logs"
  reload: False

# VLSP
# training:
#   epochs: 100
#   batch_size: 2
#   accumulation_steps: 4
#   save_path: "C:/paper/self-acoustic/save_folder"
#   train_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/train_w2i.json"
#   dev_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/val_w2i.json"
#   test_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/test_w2i.json"
#   vocab_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/vocab_w2i.json"
#   cmvn_stats : "workspace/rna/conv-rnnt/data/cmvn_stats.pt"
#   log_path: "C:/paper/self-acoustic/logs"
#   reload: False